name: test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.1
      - uses: mpizenberg/elm-tooling-action@v1.5
        with:
          cache-key: elm-home-${{ hashFiles('elm-tooling.json', 'elm.json') }}
          cache-restore-key: elm-home
      - run: elm make
      - run: elm-test-rs
      - run: elm-format src/ tests/ --validate
